export interface abilityChecksProficientType {
    athletics: boolean,
    acrobatics: boolean,
    sleightOfHand: boolean,
    stealth: boolean,
    arcana: boolean,
    history: boolean,
    investigation: boolean,
    nature: boolean,
    religion: boolean,
    animalHandling: boolean,
    insight: boolean,
    medicine: boolean,
    perception: boolean,
    survival: boolean,
    deception: boolean,
    intimidation: boolean,
    performance: boolean,
    persuasion: boolean,
}

export const defaultAbilityChecks: abilityChecksProficientType = {
    athletics: false,
    acrobatics: false,
    sleightOfHand: false,
    stealth: false,
    arcana: false,
    history: false,
    investigation: false,
    nature: false,
    religion: false,
    animalHandling: false,
    insight: false,
    medicine: false,
    perception: false,
    survival: false,
    deception: false,
    intimidation: false,
    performance: false,
    persuasion: false,
};
