export interface abilityChecksType {
    athletics: number,
    acrobatics: number,
    sleightOfHand: number,
    stealth: number,
    arcana: number,
    history: number,
    investigation: number,
    nature: number,
    religion: number,
    animalHandling: number,
    insight: number,
    medicine: number,
    perception: number,
    survival: number,
    deception: number,
    intimidation: number,
    performance: number,
    persuasion: number,
}

export const defaultAbilityChecks: abilityChecksType = {
    athletics: 0,
    acrobatics: 0,
    sleightOfHand: 0,
    stealth: 0,
    arcana: 0,
    history: 0,
    investigation: 0,
    nature: 0,
    religion: 0,
    animalHandling: 0,
    insight: 0,
    medicine: 0,
    perception: 0,
    survival: 0,
    deception: 0,
    intimidation: 0,
    performance: 0,
    persuasion: 0,
};
